using System.Net.Http.Json;
using FluentAssertions;
using HealthcareEPR.Dossier.Infrastructure.Persistence;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace HealthcareEPR.Dossier.IntegrationTests.Controllers;

public class DossierControllerTests : IClassFixture<CustomWebApplicationFactory<Program>>
{
    private readonly CustomWebApplicationFactory<Program> _factory;
    private readonly HttpClient _client;

    public DossierControllerTests(CustomWebApplicationFactory<Program> factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task AddNote_ShouldReturnOk_AndPersistToDatabase()
    {
        // Arrange
        var dossierId = _factory.TestDossierId;
        var noteContent = "Patient presents with persistent cough and fatigue.";

        // Act
        var response = await _client.PostAsJsonAsync($"/api/dossier/{dossierId}/notes", noteContent);

        // Assert
        response.EnsureSuccessStatusCode(); // Assert 200-299
        
        var noteId = await response.Content.ReadFromJsonAsync<Guid>();
        noteId.Should().NotBeEmpty();

        // Verify persistence and AI Summary generation
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<DossierDbContext>();
        
        var persistedNote = await db.SessionNotes.FindAsync(noteId);
        persistedNote.Should().NotBeNull();
        persistedNote!.RawContent.Should().Be(noteContent);
        persistedNote.DossierId.Should().Be(dossierId);
        
        // Verify AI summary was generated by the service
        persistedNote.AiSummary.Should().NotBeNullOrWhiteSpace();
        persistedNote.AiSummary.Should().Contain("[AI SUMMARY]");
    }
}
